Repository vrm-c/UniVRM, pull requests merged in 2019-05, with the labels that each got.

#243 Fix typo
  Assets/VRM/DepthFirstScheduler/MainThreadDispatcher.cs
Labels: common

#241 added DepthFirstScheduler reference to VRM.Sample
  Assets/VRM.Samples/VRM.Samples.asmdef
Labels: bug

#239 unityのwww対応
  Assets/VRM/UniGLTF/Scripts/IO/TextureLoader.cs
Labels: common, importer
