Repository vrm-c/UniVRM, pull requests merged in 2021-02, with the labels that each got.

#710 Optimize string APIs
  Assets/UniGLTF/Runtime/Extensions/StringExtensions.cs
  Assets/UniGLTF/Runtime/Extensions/glTFExtensions.cs
  Assets/UniGLTF/Runtime/UniGLTF/Format/glTFTexture.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/AnimationExporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/FileSystemStorage.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/UnityPath.cs
  Assets/VRM/Runtime/IO/VRMImporterContext.cs
Labels: enhancement

#722 Implemented VrmLib.ExpressionPreset.Surprised
  Assets/VRM10/Runtime/IO/VrmExpressionAdapter.cs
  Assets/VRM10/vrmlib/Runtime/EnumUtil.cs
  Assets/VRM10/vrmlib/Runtime/Vrm/ExpressionPreset.cs
Labels: 1.0

#748 AsIEnumerator で同期的に Task を消化するのができてない。応急処置
  Assets/UniGLTF/Runtime/UniGLTF/IO/TextureLoader/GltfTextureLoader.cs
Labels: bug

#727 VRM1 は、XYZ_RightUpForward_RH にする
  Assets/VRM10/Editor/MigrationMenu.cs
  Assets/VRM10/Editor/Vrm10ExportDialog.cs
  Assets/VRM10/Runtime/IO/BufferAccessorAdapter.cs
  Assets/VRM10/Runtime/Migration/Migration.cs
  Assets/VRM10/Runtime/Migration/MigrationCheck.cs
  Assets/VRM10/Runtime/Migration/MigrationCheck.cs.meta
  Assets/VRM10/Runtime/Migration/MigrationException.cs
  Assets/VRM10/Runtime/Migration/MigrationException.cs.meta
  Assets/VRM10/Runtime/Migration/MigrationVrm.cs
  Assets/VRM10/Runtime/Migration/MigrationVrm.cs.meta
  Assets/VRM10/Runtime/Migration/MigrationVrmExpression.cs
  Assets/VRM10/Runtime/Migration/MigrationVrmExpression.cs.meta
  Assets/VRM10/Runtime/Migration/MigrationVrmHumanoid.cs
  Assets/VRM10/Runtime/Migration/MigrationVrmHumanoid.cs.meta
  Assets/VRM10/Runtime/Migration/MigrationVrmMeta.cs
  Assets/VRM10/Runtime/Migration/MigrationVrmMeta.cs.meta
  Assets/VRM10/Runtime/Migration/MigrationVrmSpringBone.cs
  Assets/VRM10/Runtime/Migration/MigrationVrmSpringBone.cs.meta
  Assets/VRM10/Runtime/Migration/RotateY180.cs
  Assets/VRM10/Runtime/Migration/RotateY180.cs.meta
  Assets/VRM10/Runtime/Scenes/Sample.cs
  Assets/VRM10/Runtime/UnityExtensions.cs
  Assets/VRM10/Tests.PlayMode/MaterialTests.cs
  Assets/VRM10/Tests/ApiSampleTests.cs
  Assets/VRM10/Tests/MigrationTests.cs
  Assets/VRM10/vrmlib/Runtime/Coordinates.cs
  Assets/VRM10/vrmlib/Runtime/ImportExport/ModelLoader.cs
  Assets/VRM10/vrmlib/Runtime/ModelExtensionsForBvh.cs
  Assets/VRM10/vrmlib/Runtime/ModelExtensionsForCoordinates.cs
  Assets/VRM10/vrmlib/Runtime/NumericsExtensions.cs
  Assets/VRM10/vrmlib/Runtime/SpanLike.cs
  Assets/VRM10/vrmlib/Tests/ModifierTests.cs
  ProjectSettings/ProjectSettings.asset
Labels: 1.0
