Repository vrm-c/UniVRM, pull requests merged in 2021-11, with the labels that each got.

#1356 [1.0] Fix10/firstperson import fallback
  Assets/UniGLTF/Runtime/UniGLTF/UniGLTFVersion.cs
  Assets/UniGLTF/package.json
  Assets/VRM/Runtime/Format/VRMVersion.cs
  Assets/VRM/package.json
  Assets/VRM10/Runtime/IO/Vrm10Importer.cs
  Assets/VRM10/package.json
  Assets/VRMShaders/package.json
Labels: FirstPerson

#1362 glTF 形式の uri アクセスをキャッシュ(たぶん、0.87以前の動作)
  Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
Labels: importer

#1363 meshを正規化するときに、法線を正規化する
  Assets/UniGLTF/Runtime/MeshUtility/BoneNormalizer.cs
  Assets/UniGLTF/Runtime/MeshUtility/MeshExtensions.cs
Labels: bug, exporter

#1374 [1.0] indices が 65535 を超える場合に indexFormat をセットする
  Assets/VRM10/Runtime/IO/Model/MeshImporter.cs
  Assets/VRM10/Runtime/IO/Model/MeshImporterDivided.cs
Labels: bug, importer, 1.0

#1385 未知の material をエクスポートするとエラーになるのを回避
  Assets/UniGLTF/Editor/UniGLTF/ExportDialog/MaterialValidator.cs
Labels: exporter

#1397 UniGLTF において、メッシュの Bounds が計算されていなかった問題を修正
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshContext.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshImporter.cs
  Assets/VRM10/Runtime/IO/Model/MeshImporter.cs
Labels: bug
