Repository vrm-c/UniVRM, pull requests merged in 2021-04, with the labels that each got.

#860 BlendShapeの連結バグの修正
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshImporter.cs
Labels: bug, importer

#861 VertexBufferをSubMeshで分割してエクスポートするオプション
  Assets/UniGLTF/Editor/UniGLTF/GltfExportSettings.cs
  Assets/UniGLTF/Editor/UniGLTF/GltfExportWindow.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshExportSettings.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshExportSettings.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshExporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshExporterDivided.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshExporterDivided.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshWithRenderer.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
  Assets/UniGLTF/Tests/UniGLTF/MeshTests.cs
  Assets/VRM/Editor/Format/VRMExportSettings.cs
  Assets/VRM/Editor/Format/VRMExportSettingsEditor.cs
Labels: 1.0, exporter

#871 remove VRM10SpringBoneColliderGroup.Reset.
  Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneColliderGroup.cs
Labels: 1.0, bug

#870 colliderの重複を考慮していなかった
  Assets/VRM10/Runtime/IO/RuntimeUnityBuilder.cs
Labels: 1.0, bug

#872 Feature/extract key
  Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/EditorMaterial.cs
  Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/ScriptedImporterExtension.cs
  Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/ScriptedImporterImpl.cs
  Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/TextureExtractor.cs
  Assets/UniGLTF/Editor/UniGLTF/TextureImporterConfigurator.cs
  Assets/UniGLTF/MeshUtility/Editor/ExportDialog/ExportDialogState.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/GltfPBRMaterial.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/GltfTextureEnumerator.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/GltfUnlitMaterial.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/SubAssetKey.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/SubAssetKey.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/GltfTextureImporter.cs
  Assets/VRM/Editor/Format/VRMEditorImporterContext.cs
  Assets/VRM/Editor/Format/VRMImporterMenu.cs
  Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs
  Assets/VRM/Runtime/IO/MToonTextureParam.cs
  Assets/VRM/Runtime/IO/VRMImporterContext.cs
  Assets/VRM/Runtime/IO/VRMMtoonMaterialImporter.cs
  Assets/VRM/Tests/VRMTextureEnumerateTests.cs
  Assets/VRM10/Editor/ScriptedImporter/EditorVrm.cs
  Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterImpl.cs
  Assets/VRM10/Runtime/Components/Expression/ExpressionKey.cs
  Assets/VRM10/Runtime/Components/Expression/VRM10ExpressionAvatar.cs
  Assets/VRM10/Runtime/Components/Meta/VRM10MetaObject.cs
  Assets/VRM10/Runtime/IO/ExpressionExtensions.cs
  Assets/VRM10/Runtime/IO/RuntimeUnityBuilder.cs
  Assets/VRM10/Runtime/IO/Vrm10MToonMaterialImporter.cs
  Assets/VRMShaders/GLTF/IO/Runtime/TextureFactory.cs
  Assets/VRMShaders/GLTF/IO/Runtime/TextureImportName.cs
  Assets/VRMShaders/GLTF/IO/Runtime/TextureImportParam.cs
Labels: importer

#890 Fix/texture extract subassetkey
  Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/TextureExtractor.cs
  Assets/UniGLTF/Tests/UniGLTF/TextureTests.cs
Labels: bug

#895 Feature/tpose button
  Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs
  Assets/UniGLTF/Editor/UniGLTF/ExportDialog/GltfExportWindow.cs
  Assets/UniGLTF/Editor/UniGLTF/ExportDialog/InternalTPose.cs
  Assets/UniGLTF/Editor/UniGLTF/ExportDialog/InternalTPose.cs.meta
  Assets/VRM/Editor/Format/VRMExportSettingsEditor.cs
  Assets/VRM/Editor/Format/VRMExporterWizard.cs
  Assets/VRM10/Editor/Vrm10ExportDialog.cs
Labels: bug

#896 [1.0]MToon export の実装
  Assets/VRM10/Runtime/IO/MeshAdapter.cs
  Assets/VRM10/Runtime/IO/Vrm10Exporter.cs
  Assets/VRM10/Runtime/IO/Vrm10MaterialExporter.cs
  Assets/VRM10/Runtime/IO/Vrm10MaterialImporter.cs
Labels: 1.0

#899 同一のMeshとMaterialを参照しているNodeをExportする場合に、重複をチェックして同じMeshIndexを参照するように変更
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshWithRenderer.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
Labels: exporter, glTF

#912 Fix/mesh export divided
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshExporterDivided.cs
  Assets/VRM/Tests/VrmDividedMeshTests.cs
  Assets/VRM/Tests/VrmDividedMeshTests.cs.meta
Labels: bug
