Repository vrm-c/UniVRM, pull requests merged in 2024-07, with the labels that each got.

#2338 VRM-1.0 の export 時に Animator の代替に UniHumanoid.Humanoid を使う
  Assets/UniGLTF/Editor/UniGLTF.Editor.asmdef
  Assets/UniGLTF/Editor/UniGLTF/Validation/HumanoidValidator.cs
Labels: exporter, editor, 1.0

#2340 Add PullRequest Label checker
  .github/workflows/label_checker.yml
Labels: Non breaking changes

#2339 boneWeights コピー忘れ
  Assets/UniGLTF/Runtime/MeshUtility/MeshFreezer.cs
Labels: bug, exporter, mesh, Non breaking changes

#2341 [0.x][1.0] SkinnedMeshRenderer.bones に null が含まれていてもExportできる
  Assets/UniGLTF/Runtime/MeshUtility/MeshAttachInfo.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/NodeImporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
  Assets/VRM/Runtime/Extensions/VrmHumanoidExtensions.cs
  Assets/VRM10/Runtime/IO/Model/ModelExporter.cs
  Assets/VRM10/Runtime/IO/Vrm10Exporter.cs
Labels: exporter, mesh, Non breaking changes

#2343 Update Label Checker
  .github/workflows/label_checker.yml
Labels: Non breaking changes

#2344 Suppress shader compile errors when URP is not imported.
  Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_urp.shader
Labels: Non breaking changes

#2355 Maintain extension support flags when migrating a vrm0.x model.
  Assets/UniGLTF/Runtime/UniGLTF/IO/ExtensionSupportFlags.cs
  Assets/VRM10/Runtime/IO/Vrm10Data.cs
Labels: Non breaking changes

#2336 [SpringBone] inspector改修
  Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneColliderEditor.cs
  Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs
  Assets/VRM10/Runtime/AssemblyInfo.cs
  Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneCollider.cs
  Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneJoint.cs
  Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs
  Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10InstanceSpringBone.cs
Labels: SpringBone, Non breaking changes

#2362 UniGLTFLogger を追加
  Assets/UniGLTF/Editor/MeshUtility/MeshUtilityDialog.cs
  Assets/UniGLTF/Editor/MeshUtility/PrefabContext.cs
  Assets/UniGLTF/Editor/MeshUtility/TabBoneMeshRemover.cs
  Assets/UniGLTF/Editor/MeshUtility/TabMeshSeparator.cs
  Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogState.cs
  Assets/UniGLTF/Editor/UniGLTF/Gizmo/BoneSelector.cs
  Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporterBase.cs
  Assets/UniGLTF/Editor/UniGLTF/UniGLTFPreference.cs
  Assets/UniGLTF/Editor/UniHumanoid/BoneMappingEditor.cs
  Assets/UniGLTF/Editor/UniHumanoid/HumanoidEditor.cs
  Assets/UniGLTF/Editor/UniHumanoid/MuscleInspectorEditor.cs
  Assets/UniGLTF/Editor/UniHumanoid/UniHumanoid.Editor.asmdef
  Assets/UniGLTF/Editor/UniHumanoid/bvhAssetPostprocessor.cs
  Assets/UniGLTF/Runtime/MeshUtility/MeshExclude.cs
  Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrator.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshData.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshUploader.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/Parser/GlbLowLevelParser.cs
  Assets/UniGLTF/Runtime/UniHumanoid/IO/BvhImporterContext.cs
  Assets/UniGLTF/Runtime/UniJSON/ConcreteCast.cs
  Assets/UniGLTF/Runtime/Utils/UniGLTFLogger.cs
  Assets/UniGLTF/Runtime/Utils/UniGLTFLogger.cs.meta
  Assets/VRM/Editor/BlendShape/PreviewEditor.cs
  Assets/VRM/Editor/Format/VRMAssetWriter.cs
  Assets/VRM/Editor/Format/VRMEditorExporter.cs
  Assets/VRM/Editor/Format/VRMEditorImporterContext.cs
  Assets/VRM/Runtime/BlendShape/BlendShapeAvatar.cs
  Assets/VRM/Runtime/BlendShape/PreviewSceneManager.cs
  Assets/VRM/Runtime/IO/MaterialIO/BuiltInRP/Export/BuiltInVrmExtensionMaterialPropertyExporter.cs
  Assets/VRM10/Editor/Components/Expression/VRM10ExpressionEditor.cs
  Assets/VRM10/Editor/PackageResource.cs
  Assets/VRM10/Runtime/Components/Expression/Preview/PreviewSceneManager.cs
  Assets/VRM10/Runtime/Components/Expression/PreviewMaterialItem.cs
  Assets/VRM10/Runtime/StringExtensions.cs
Labels: Non breaking changes

#2363 add BlittableExternalData.Paused
  Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs
  Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs
  Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs.meta
  Assets/VRM10/Runtime/FastSpringBone/Blittables/BlittableExternalData.cs
  Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBuffer.cs
  Assets/VRM10/Runtime/FastSpringBone/System/UpdateFastSpringBoneJob.cs
  Assets/VRM10_Samples/VRM10Viewer/VRM10Loaded.cs
  Assets/VRM10_Samples/VRM10Viewer/VRM10Viewer.unity
  Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs
Labels: SpringBone, Non breaking changes

#2371 root の子孫に再帰的に joint を設定するボタン
  Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneDrawer.cs
  Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneDrawer.cs.meta
Labels: SpringBone, editor, Non breaking changes

#2374 UniVRM-0.124.2
  Assets/UniGLTF/Runtime/UniGLTF/PackageVersion.cs
  Assets/UniGLTF/Runtime/UniGLTF/UniGLTFVersion.cs
  Assets/UniGLTF/package.json
  Assets/VRM/package.json
  Assets/VRM10/Samples~/VRM10Viewer/VRM10Loaded.cs
  Assets/VRM10/Samples~/VRM10Viewer/VRM10Viewer.unity
  Assets/VRM10/Samples~/VRM10Viewer/VRM10ViewerUI.cs
  Assets/VRM10/package.json
  Assets/VRMShaders/package.json
Labels: Non breaking changes

#2375 URP プロジェクトで matcap を含むモデルを Editor import するとエラーになるのを回避(暫定)
  Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/TextureExtractor.cs
Labels: importer, material/texture, Non breaking changes

#2365 Move VRM10 material format definitions from VRMShaders to VRM10
  Assets/VRM10/Editor/Vrm10SerializerGenerator.cs
  Assets/VRM10/Runtime/Format/MaterialsMToon/Format.g.cs
  Assets/VRM10/Runtime/Format/MaterialsMToon/Format.g.cs.meta
  Assets/VRMShaders/VRM10/Format.meta
  Assets/VRMShaders/VRM10/Format/Runtime.meta
  Assets/VRMShaders/VRM10/Format/Runtime/MaterialsMToon.meta
  Assets/VRMShaders/VRM10/Format/Runtime/VRMShaders.VRM10.Format.Runtime.asmdef
  Assets/VRMShaders/VRM10/Format/Runtime/VRMShaders.VRM10.Format.Runtime.asmdef.meta
Labels: material/texture, Breaking changes

#2370 Move MToon0.X material definitions from VRMShaders to VRM
  Assets/VRM/MToon.meta
  Assets/VRM/MToon/Editor.meta
  Assets/VRM/MToon/Editor/EditorEnums.cs
  Assets/VRM/MToon/Editor/EditorEnums.cs.meta
  Assets/VRM/MToon/Editor/EditorUtils.cs
  Assets/VRM/MToon/Editor/EditorUtils.cs.meta
  Assets/VRM/MToon/Editor/MToon.Editor.asmdef
  Assets/VRM/MToon/Editor/MToon.Editor.asmdef.meta
  Assets/VRM/MToon/Editor/MToonInspector.cs
  Assets/VRM/MToon/Editor/MToonInspector.cs.meta
  Assets/VRM/MToon/LICENSE
  Assets/VRM/MToon/LICENSE.meta
  Assets/VRM/MToon/README.md
  Assets/VRM/MToon/README.md.meta
  Assets/VRM/MToon/Resources.meta
  Assets/VRM/MToon/Resources/Shaders.meta
  Assets/VRM/MToon/Resources/Shaders/MToon.shader
  Assets/VRM/MToon/Resources/Shaders/MToon.shader.meta
  Assets/VRM/MToon/Resources/Shaders/MToonCore.cginc
  Assets/VRM/MToon/Resources/Shaders/MToonCore.cginc.meta
  Assets/VRM/MToon/Resources/Shaders/MToonSM3.cginc
  Assets/VRM/MToon/Resources/Shaders/MToonSM3.cginc.meta
  Assets/VRM/MToon/Resources/Shaders/MToonSM4.cginc
  Assets/VRM/MToon/Resources/Shaders/MToonSM4.cginc.meta
  Assets/VRM/MToon/Runtime.meta
  Assets/VRM/MToon/Runtime/Enums.cs
  Assets/VRM/MToon/Runtime/Enums.cs.meta
  Assets/VRM/MToon/Runtime/MToon.asmdef
  Assets/VRM/MToon/Runtime/MToon.asmdef.meta
  Assets/VRM/MToon/Runtime/MToonDefinition.cs
  Assets/VRM/MToon/Runtime/MToonDefinition.cs.meta
  Assets/VRM/MToon/Runtime/Utils.cs
  Assets/VRM/MToon/Runtime/Utils.cs.meta
  Assets/VRM/MToon/Runtime/UtilsGetter.cs
  Assets/VRM/MToon/Runtime/UtilsGetter.cs.meta
  Assets/VRM/MToon/Runtime/UtilsSetter.cs
  Assets/VRM/MToon/Runtime/UtilsSetter.cs.meta
  Assets/VRM/MToon/Runtime/UtilsVersion.cs
  Assets/VRM/MToon/Runtime/UtilsVersion.cs.meta
  Assets/VRM/MToon/Samples.meta
  Assets/VRM/MToon/Samples/Materials.meta
  Assets/VRM/MToon/Samples/Materials/Ex_OutlineWidth_Screen.mat
  Assets/VRM/MToon/Samples/Materials/Ex_OutlineWidth_Screen.mat.meta
  Assets/VRM/MToon/Samples/Materials/Ex_OutlineWidth_World.mat
  Assets/VRM/MToon/Samples/Materials/Ex_OutlineWidth_World.mat.meta
  Assets/VRM/MToon/Samples/Materials/Ground.mat
  Assets/VRM/MToon/Samples/Materials/Ground.mat.meta
  Assets/VRM/MToon/Samples/Materials/Toon.mat
  Assets/VRM/MToon/Samples/Materials/Toon.mat.meta
  Assets/VRM/MToon/Samples/OutlineWidthModes.unity
  Assets/VRM/MToon/Samples/OutlineWidthModes.unity.meta
  Assets/VRMShaders/VRM/MToon.meta
  Assets/VRMShaders/VRM/MToon/.gitignore
Labels: material/texture, Breaking changes

#2372 Move UniUnlit material definitions from VRMShaders to UniGLTF
  Assets/UniGLTF/UniUnlit.meta
  Assets/UniGLTF/UniUnlit/Editor.meta
  Assets/UniGLTF/UniUnlit/Editor/UniGLTF.UniUnlit.Editor.asmdef
  Assets/UniGLTF/UniUnlit/Editor/UniGLTF.UniUnlit.Editor.asmdef.meta
  Assets/UniGLTF/UniUnlit/Editor/UniUnlitEditor.cs
  Assets/UniGLTF/UniUnlit/Editor/UniUnlitEditor.cs.meta
  Assets/UniGLTF/UniUnlit/Resources.meta
  Assets/UniGLTF/UniUnlit/Resources/UniGLTF.meta
  Assets/UniGLTF/UniUnlit/Resources/UniGLTF/UniUnlit.shader
  Assets/UniGLTF/UniUnlit/Resources/UniGLTF/UniUnlit.shader.meta
  Assets/UniGLTF/UniUnlit/Runtime.meta
  Assets/UniGLTF/UniUnlit/Runtime/UniGLTF.UniUnlit.asmdef
  Assets/UniGLTF/UniUnlit/Runtime/UniGLTF.UniUnlit.asmdef.meta
  Assets/UniGLTF/UniUnlit/Runtime/UniUnlitUtil.cs
  Assets/UniGLTF/UniUnlit/Runtime/UniUnlitUtil.cs.meta
Labels: material/texture, Breaking changes

#2377 Delete VRMShaders (com.vrm-c.vrmshaders) UPM Package
  Assets/UniGLTF/package.json
  Assets/VRM/Editor/Format/VRMVersionMenu.cs
  Assets/VRM/Settings.meta
  Assets/VRM/Settings/VRMShaders.shadervariants
  Assets/VRM/Settings/VRMShaders.shadervariants.meta
  Assets/VRM/package.json
  Assets/VRM10/Settings.meta
  Assets/VRM10/Settings/VRM10Shaders.shadervariants
  Assets/VRM10/Settings/VRM10Shaders.shadervariants.meta
  Assets/VRM10/package.json
  Assets/VRMShaders.meta
  Assets/VRMShaders/CHANGELOG.md
  Assets/VRMShaders/CHANGELOG.md.meta
  Assets/VRMShaders/Documentation.meta
  Assets/VRMShaders/Documentation/VRMShaders.md
  Assets/VRMShaders/Documentation/VRMShaders.md.meta
  Assets/VRMShaders/GLTF.meta
  Assets/VRMShaders/LICENSE.md
  Assets/VRMShaders/LICENSE.md.meta
  Assets/VRMShaders/README.md
  Assets/VRMShaders/VRM10.meta
  Assets/VRMShaders/package.json
  Assets/VRMShaders/package.json.meta
Labels: Breaking changes

#2378 Use URP as default in development project.
  Assets/Development.meta
  Assets/Development/Editor.meta
  Assets/Development/Editor/Development.Editor.asmdef
  Assets/Development/Editor/Development.Editor.asmdef.meta
  Assets/Development/Runtime.meta
  Assets/Development/Runtime/Development.asmdef
  Assets/Development/Runtime/Development.asmdef.meta
  Assets/Development/Settings.meta
  Assets/Development/Settings/URP.asset
  Assets/Development/Settings/URP.asset.meta
  Assets/Development/Settings/URP_Renderer.asset
  Assets/Development/Settings/URP_Renderer.asset.meta
  Assets/UniversalRenderPipelineGlobalSettings.asset
  Assets/UniversalRenderPipelineGlobalSettings.asset.meta
  ProjectSettings/GraphicsSettings.asset
Labels: Non breaking changes

#2379 VRM10Viewer supports both Built-in and URP
  Assets/VRM10_Samples/VRM10Viewer/Motions/BvhMotion.cs
  Assets/VRM10_Samples/VRM10Viewer/VRM10TargetMover.cs
  Assets/VRM10_Samples/VRM10Viewer/VRM10Viewer.unity
  Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs
  Assets/VRM10_Samples/VRM10Viewer/VRM10VisualPrimitive.cs
  Assets/VRM10_Samples/VRM10Viewer/VRM10VisualPrimitive.cs.meta
Labels: Non breaking changes

#2382 fix: add missing System namespace on Unity 6
  Assets/VRM10/MToon10/Runtime/MToonOutlineRenderPass.cs
Labels: material/texture, Non breaking changes

#2383 fix VRM10SpringBoneJointEditor
  Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs
Labels: SpringBone, editor, Non breaking changes

#2385 Ignore using Task<T>.Wait()
  Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Import/MaterialFactory.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshUploader.cs
  Assets/VRM10/Runtime/IO/Vrm10Importer.cs
Labels: Non breaking changes

#2390 gltf/vrm/vrm10 exporters consider RenderPipelines
  Assets/UniGLTF/Editor/UniGLTF/ExportDialog/GltfExportWindow.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Export/MaterialExporterUtility.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Export/MaterialExporterUtility.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Import/MaterialDescriptorGeneratorUtility.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Import/MaterialDescriptorGeneratorUtility.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/RenderPipelineUtility.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/RenderPipelineUtility.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
  Assets/UniGLTF/Tests/UniGLTF/EditorTextureSerializerTests.cs
  Assets/UniGLTF/Tests/UniGLTF/GltfLoadTests.cs
  Assets/UniGLTF/Tests/UniGLTF/UniGLTFTests.cs
  Assets/VRM/Editor/Format/VRMEditorExporter.cs
  Assets/VRM/Runtime/IO/MaterialIO/VrmMaterialDescriptorGeneratorUtility.cs
  Assets/VRM/Runtime/IO/MaterialIO/VrmMaterialDescriptorGeneratorUtility.cs.meta
  Assets/VRM/Runtime/IO/MaterialIO/VrmMaterialExporterUtility.cs
  Assets/VRM/Runtime/IO/MaterialIO/VrmMaterialExporterUtility.cs.meta
  Assets/VRM/Runtime/IO/VRMExporter.cs
  Assets/VRM10/Editor/Vrm10ExportDialog.cs
  Assets/VRM10/Runtime/IO/Material/Vrm10MaterialDescriptorGeneratorUtility.cs
  Assets/VRM10/Runtime/IO/Material/Vrm10MaterialDescriptorGeneratorUtility.cs.meta
  Assets/VRM10/Runtime/IO/Material/Vrm10MaterialExporterUtility.cs
  Assets/VRM10/Runtime/IO/Material/Vrm10MaterialExporterUtility.cs.meta
  Assets/VRM10/Runtime/IO/Vrm10Exporter.cs
  Assets/VRM10/Runtime/IO/Vrm10Importer.cs
  Assets/VRM10/Runtime/IO/VrmAnimationExporter.cs
  Assets/VRM10/Tests/ApiSampleTests.cs
  Assets/VRM10_Samples/VRM10RuntimeExporterSample/VRM10RuntimeExporter.cs
Labels: Breaking changes

#2391 Pass tests in URP project settings
  Assets/UniGLTF/Tests/Objects.meta
  Assets/UniGLTF/Tests/Objects/4x4_gray_import_as_linear.png
  Assets/UniGLTF/Tests/Objects/4x4_gray_import_as_linear.png.meta
  Assets/UniGLTF/Tests/Objects/4x4_gray_import_as_normal_map.png
  Assets/UniGLTF/Tests/Objects/4x4_gray_import_as_normal_map.png.meta
  Assets/UniGLTF/Tests/Objects/4x4_gray_import_as_srgb.png
  Assets/UniGLTF/Tests/Objects/4x4_gray_import_as_srgb.png.meta
  Assets/UniGLTF/Tests/Objects/4x4_non_readable.png
  Assets/UniGLTF/Tests/Objects/4x4_non_readable.png.meta
  Assets/UniGLTF/Tests/Objects/4x4_non_readable_compressed.DDS
  Assets/UniGLTF/Tests/Objects/4x4_non_readable_compressed.DDS.meta
  Assets/UniGLTF/Tests/Objects/New Material.mat
  Assets/UniGLTF/Tests/Objects/New Material.mat.meta
  Assets/UniGLTF/Tests/UniGLTF/AssetTests.cs
  Assets/UniGLTF/Tests/UniGLTF/CopyTextureTests.cs
  Assets/UniGLTF/Tests/UniGLTF/EditorTextureSerializerTests.cs
  Assets/UniGLTF/Tests/UniGLTF/TestAssets.cs
  Assets/UniGLTF/Tests/UniGLTF/TestAssets.cs.meta
  Assets/UniGLTF/Tests/UniGLTF/TestGltf.cs
  Assets/UniGLTF/Tests/UniGLTF/TestGltf.cs.meta
  Assets/UniGLTF/Tests/UniGLTF/TextureBytesTests.cs
  Assets/UniGLTF/Tests/UniGLTF/UniGLTFTests.cs
  Assets/VRM/Editor/Format/VRMEditorExporter.cs
  Assets/VRM/Tests/SampleTests/VRMImportExportTests.cs
  Assets/VRM/Tests/TestVrm0X.cs
  Assets/VRM/Tests/TestVrm0X.cs.meta
  Assets/VRM/Tests/VRMLookAtTests.cs
  Assets/VRM/Tests/VrmDividedMeshTests.cs
  Assets/VRM10/Tests/ApiSampleTests.cs
  Assets/VRM10/Tests/MigrationTests.cs
  Assets/VRM10/Tests/TestAsset.cs
  Assets/VRM10/Tests/TestVrm10.cs
  Assets/VRM10/Tests/TestVrm10.cs.meta
Labels: Non breaking changes

#2393 glTF/VRM1.0 ScriptedImporters can detect the project's RenderPipeline. or a user can select manually.
  Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporterBase.cs
  Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/ImporterRenderPipelineTypes.cs
  Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/ImporterRenderPipelineTypes.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Import/MaterialDescriptorGeneratorUtility.cs
  Assets/VRM/Runtime/IO/MaterialIO/VrmMaterialDescriptorGeneratorUtility.cs
  Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporter.cs
  Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterImpl.cs
  Assets/VRM10/Runtime/IO/Material/Vrm10MaterialDescriptorGeneratorUtility.cs
Labels: Non breaking changes

#2392 fix: Add spec version `1.0` to `VRMC_springBone_extended_collider`
  Assets/VRM10/Runtime/IO/Vrm10Exporter.cs
Labels: exporter, SpringBone, 1.0, Non breaking changes
