Repository vrm-c/UniVRM, pull requests merged in 2024-08, with the labels that each got.

#2394 Implements glTF PBR material import/export at URP
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Export/GltfMaterialExportUtils.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Export/MaterialExporterUtility.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Import/MaterialDescriptor.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Import/MaterialFactory.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/Materials.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/Materials/UrpLitMaterialExporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/Materials/UrpLitMaterialExporter.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/UrpGltfMaterialExporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/UrpGltfMaterialExporter.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/Materials/UrpGltfPbrMaterialImporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitBlendMode.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitBlendMode.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitContext.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitContext.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitSmoothnessMapChannel.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitSmoothnessMapChannel.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitSurfaceType.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitSurfaceType.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitWorkflowType.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitWorkflowType.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Utils.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Utils/InternalMaterialUtils.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Utils/InternalMaterialUtils.cs.meta
Labels: importer, exporter, material/texture, Non breaking changes

#2395 Implements glTF default material importer at URP
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/BuiltInGltfMaterialDescriptorGenerator.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/Materials/BuiltInGltfDefaultMaterialImporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Import/IMaterialDescriptorGenerator.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/Materials/UrpGltfDefaultMaterialImporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/Materials/UrpGltfPbrMaterialImporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/UrpGltfMaterialDescriptorGenerator.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitContext.cs
  Assets/VRM/Runtime/IO/MaterialIO/BuiltInRP/Import/BuiltInVrmMaterialDescriptorGenerator.cs
  Assets/VRM/Runtime/IO/MaterialIO/URP/Import/UrpVrmMaterialDescriptorGenerator.cs
  Assets/VRM10/Runtime/IO/Material/BuiltInRP/Import/BuiltInVrm10MaterialDescriptorGenerator.cs
  Assets/VRM10/Runtime/IO/Material/URP/Import/UrpVrm10MaterialDescriptorGenerator.cs
Labels: importer, material/texture, URP, Breaking changes

#2396 Remember instance assigning
  Assets/VRM/Runtime/IO/MaterialIO/URP/Import/UrpVrmMaterialDescriptorGenerator.cs
  Assets/VRM10/Runtime/IO/Material/URP/Import/UrpVrm10MaterialDescriptorGenerator.cs
Labels: Non breaking changes

#2398 UniVRM-0.125.0
  Assets/UniGLTF/Runtime/UniGLTF/PackageVersion.cs
  Assets/UniGLTF/Runtime/UniGLTF/UniGLTFVersion.cs
  Assets/UniGLTF/Samples~/GltfViewer/GltfViewer.cs
  Assets/UniGLTF/Samples~/GltfViewer/OpenFileDialog/OpenFileDialog.cs
  Assets/UniGLTF/Samples~/UniHumanoid/HumanBuilderTest.cs
  Assets/UniGLTF/package.json
  Assets/VRM/Samples~/FirstPersonSample/VRMRuntimeLoader.cs
  Assets/VRM/Samples~/RuntimeExporterSample/VRMRuntimeExporter.cs
  Assets/VRM/Samples~/SimpleViewer/ViewerUI.cs
  Assets/VRM/package.json
  Assets/VRM10/Samples~/SimpleVrma/SimpleVrma.cs
  Assets/VRM10/Samples~/URPSample/Runtime/UrpSampleUI.cs
  Assets/VRM10/Samples~/VRM10FirstPersonSample/VRM10RuntimeLoader.cs
  Assets/VRM10/Samples~/VRM10RuntimeExporterSample/VRM10RuntimeExporter.cs
  Assets/VRM10/Samples~/VRM10Viewer/Motions/BvhMotion.cs
  Assets/VRM10/Samples~/VRM10Viewer/VRM10TargetMover.cs
  Assets/VRM10/Samples~/VRM10Viewer/VRM10Viewer.unity
  Assets/VRM10/Samples~/VRM10Viewer/VRM10ViewerUI.cs
  Assets/VRM10/Samples~/VRM10Viewer/VRM10VisualPrimitive.cs
  Assets/VRM10/Samples~/VRM10Viewer/VRM10VisualPrimitive.cs.meta
  Assets/VRM10/package.json
  ProjectSettings/UnityConnectSettings.asset
Labels: Non breaking changes

#2400 Implements exporting materials in URP
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/Materials/UrpFallbackMaterialExporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/Materials/UrpFallbackMaterialExporter.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/Materials/UrpLitMaterialExporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/Materials/UrpUniUnlitMaterialExporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/Materials/UrpUniUnlitMaterialExporter.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/Materials/UrpUnlitMaterialExporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/Materials/UrpUnlitMaterialExporter.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Export/UrpGltfMaterialExporter.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpBaseShaderContext.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpBaseShaderContext.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitContext.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpUnlitContext.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpUnlitContext.cs.meta
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Utils/UniGLTFShaderNotMatchedInternalException.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Utils/UniGLTFShaderNotMatchedInternalException.cs.meta
  Assets/UniGLTF/UniUnlit/Runtime/UniUnlitContext.cs
  Assets/UniGLTF/UniUnlit/Runtime/UniUnlitContext.cs.meta
Labels: Non breaking changes

#2401 [VRMA] Fixed an issue where a shader could not be found at app
  Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Import/MaterialFactory.cs
  Assets/VRM10/Runtime/Components/VrmAnimationInstance/Vrm10AnimationInstance.cs
  Assets/VRM10/Runtime/IO/VrmAnimationImporter.cs
Labels: animation, Non breaking changes

#2397 Update README.md
  README.md
Labels: Non breaking changes

#2406 Vrm10RuntimeSpringBoneのファイルパス修正、およびtypoを修正
  Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone.cs
  Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone.cs.meta
Labels: Non breaking changes

#2413 テクスチャの含まれないVRMのExport時、Buffer ByteLentghが正しく出力されない問題を修正しました。
  Assets/UniGLTF/Runtime/UniGLTF/IO/ExportingGltfData.cs
Labels: exporter, glTF, Non breaking changes

#2405 Add ImporterContextSettings to specify LoadAnimation and InvertAxes in ImporterContext
  Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporterBase.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContextSettings.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContextSettings.cs.meta
  Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs
  Assets/VRM/Runtime/IO/VRMImporterContext.cs
  Assets/VRM/Runtime/IO/VrmUtility.cs
  Assets/VRM10/Runtime/IO/Vrm10.cs
  Assets/VRM10/Runtime/IO/Vrm10Importer.cs
  Assets/VRM10/Runtime/IO/VrmAnimationImporter.cs
Labels: Breaking changes

#2414 [vrm1] mesh export 時の byteLength 確認テストを追加
  Assets/UniGLTF/Tests/UniGLTF/UniGLTFTests.cs
  Assets/VRM10/Runtime/IO/Material/URP/Export.meta
  Assets/VRM10/Runtime/IO/Material/URP/Export/UrpVrm10MaterialExporter.cs
  Assets/VRM10/Runtime/IO/Material/URP/Export/UrpVrm10MaterialExporter.cs.meta
  Assets/VRM10/Runtime/IO/Material/Vrm10MaterialExporterUtility.cs
  Assets/VRM10/Tests/LoadTests.cs
Labels: editor, Non breaking changes

#2416 [vrm-1.0][editor][play] SpringBone の変更時に反映呼び出し
  Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneColliderEditor.cs
  Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs
Labels: SpringBone, editor, 1.0, Non breaking changes
