Repository vrm-c/UniVRM, pull requests merged in 2025-05, with the labels that each got.

#2653 Fix NativeArrayManager compatibility with Unity 2022.1 and older versions
  Assets/UniGLTF/Runtime/UniGLTF/IO/NativeArrayManager.cs
Labels: UnityVersion, Non breaking changes

#2659 RuntimeGltfInstance が無い場合に NullReferenceException を修正
  Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs
  Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs
Labels: Non breaking changes

#2662 chore: Reuse `positions` to eliminate redundant `ToArray()`
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshUploader.cs
Labels: importer, mesh, Non breaking changes

#2658 [package] 厳格に空の状態から依存を解決できるようにする
  Assets/UniGLTF/package.json
  Assets/VRM/Editor/Format/VRMVersionMenu.cs
Labels: Packaging, Non breaking changes

#2663 UniVRM-0.129.1
  Assets/UniGLTF/Runtime/UniGLTF/PackageVersion.cs
  Assets/UniGLTF/Runtime/UniGLTF/UniGLTFVersion.cs
  Assets/UniGLTF/package.json
  Assets/VRM/package.json
  Assets/VRM10/package.json
Labels: Non breaking changes

#2664 fix(tangent): binarize tangent.w to ±1 to prevent NaNs and artifacts
  Assets/VRM10/MToon10/Shaders/vrmc_materials_mtoon_utility.hlsl
Labels: importer, material/texture, mesh, Non breaking changes

#2669 Unity6.0で開いて変わったところ
  Assets/DefaultVolumeProfile.asset
  Assets/DefaultVolumeProfile.asset.meta
  Assets/Development/Settings/URP.asset
  Assets/Development/Settings/URP_Renderer.asset
  Assets/UniversalRenderPipelineGlobalSettings.asset
  Assets/VRM10_Samples/ClothSample/ClothViewer/Motions/BvhMotion.cs
  Assets/VRM10_Samples/VRM10Viewer/FaceCameraTarget.asset
  Assets/VRM10_Samples/VRM10Viewer/UIToolkit/VRM10MainView.cs
  Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerController.cs
  Assets/VRM10_Samples/VRM10Viewer/VRM10VisualPrimitive.cs
  Assets/VRM10_Samples/VRM10Viewer/uGui/VRM10ViewerUI.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/MultiplayerManager.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/ShaderGraphSettings.asset
  ProjectSettings/TagManager.asset
  ProjectSettings/URPProjectSettings.asset
Labels: UnityVersion, Breaking changes
