Repository vrm-c/UniVRM, pull requests merged in 2025-02, with the labels that each got.

#2568 Updated the supported library versions for previous Unity versions in the README.
  README.md
Labels: Non breaking changes

#2570 Unity6でGraphicsSettings.renderPipelineAssetがObsolete警告を出すのに対応
  Assets/VRM/Editor/BuildClass.cs
Labels: UnityVersion, Non breaking changes

#2573 _MainTex_ST の参照を修正
  Assets/VRM10/Runtime/Components/Expression/MaterialValueBindingMerger.cs
  Assets/VRM10/Runtime/Components/Expression/PreviewMaterialItem.cs
  Assets/VRM10/Runtime/Components/VrmAnimationInstance/IVrm10Animation.cs
  Assets/VRM10/Runtime/Components/VrmAnimationInstance/Vrm10AnimationInstance.cs
  Assets/VRM10/Runtime/Components/VrmAnimationInstance/Vrm10TPose.cs
  Assets/VRM10_Samples/ClothSample/ClothViewer/Motions/BvhMotion.cs
  Assets/VRM10_Samples/VRM10Viewer/Assets.meta
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyPbr.shadergraph
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyPbr.shadergraph.meta
  Assets/VRM10_Samples/VRM10Viewer/Motions/BvhMotion.cs
  Assets/VRM10_Samples/VRM10Viewer/TinyPbrContext.cs
  Assets/VRM10_Samples/VRM10Viewer/TinyPbrContext.cs.meta
  Assets/VRM10_Samples/VRM10Viewer/TinyPbrDescriptorGenerator.cs
  Assets/VRM10_Samples/VRM10Viewer/TinyPbrDescriptorGenerator.cs.meta
  Assets/VRM10_Samples/VRM10Viewer/VRM10Viewer.unity
  Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs
  Assets/VRM10_Samples/VRM10Viewer/VRM10VisualPrimitive.cs
Labels: material/texture, Non breaking changes

#2574 [fix action dependency] update workflow
  .github/workflows/build-webgl.yml
Labels: document/sample, Non breaking changes, WebGL

#2575 vrm の root 以外にアタッチするスクリプトはアイコン取りやめ
  Assets/VRM/Runtime/SpringBone/VRMSpringBone.cs.meta
  Assets/VRM10/Runtime/Components/Constraint/Vrm10AimConstraint.cs.meta
  Assets/VRM10/Runtime/Components/Constraint/Vrm10RollConstraint.cs.meta
  Assets/VRM10/Runtime/Components/Constraint/Vrm10RotationConstraint.cs.meta
  Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneColliderGroup.cs.meta
Labels: editor, Non breaking changes

#2577 [URP][vrm10viewer] ShaderGraph material sample
  Assets/UniGLTF/Runtime/Scenes/LookDev/RenderingServicePostProcessingProfile.asset
  Assets/VRM10/Runtime/IO/Texture/Vrm10MToonTextureImporter.cs
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyMToonAlphaBlend.shadergraph
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyMToonAlphaBlend.shadergraph.meta
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyMToonOpaque.shadergraph
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyMToonOpaque.shadergraph.meta
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyMToon_SubGraph.shadersubgraph
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyMToon_SubGraph.shadersubgraph.meta
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyPbr.shadergraph
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyPbrAlphaBlend.shadergraph
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyPbrAlphaBlend.shadergraph.meta
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyPbrOpaque.shadergraph
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyPbrOpaque.shadergraph.meta
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyPbr_SubGraph.shadersubgraph
  Assets/VRM10_Samples/VRM10Viewer/Assets/TinyPbr_SubGraph.shadersubgraph.meta
  Assets/VRM10_Samples/VRM10Viewer/Assets/black.png
  Assets/VRM10_Samples/VRM10Viewer/Assets/black.png.meta
  Assets/VRM10_Samples/VRM10Viewer/Assets/blue.png
  Assets/VRM10_Samples/VRM10Viewer/Assets/blue.png.meta
  Assets/VRM10_Samples/VRM10Viewer/Assets/red.png
  Assets/VRM10_Samples/VRM10Viewer/Assets/red.png.meta
  Assets/VRM10_Samples/VRM10Viewer/Assets/white.png
  Assets/VRM10_Samples/VRM10Viewer/Assets/white.png.meta
  Assets/VRM10_Samples/VRM10Viewer/Assets/white_hdr.hdr
  Assets/VRM10_Samples/VRM10Viewer/Assets/white_hdr.hdr.meta
  Assets/VRM10_Samples/VRM10Viewer/IMaterialImporter.cs
  Assets/VRM10_Samples/VRM10Viewer/IMaterialImporter.cs.meta
  Assets/VRM10_Samples/VRM10Viewer/OrderedMaterialDescriptorGenerator.cs
  Assets/VRM10_Samples/VRM10Viewer/OrderedMaterialDescriptorGenerator.cs.meta
  Assets/VRM10_Samples/VRM10Viewer/TinyMToonMaterialContext.cs
  Assets/VRM10_Samples/VRM10Viewer/TinyMToonMaterialContext.cs.meta
  Assets/VRM10_Samples/VRM10Viewer/TinyMToonMaterialImporter.cs
  Assets/VRM10_Samples/VRM10Viewer/TinyMToonMaterialImporter.cs.meta
  Assets/VRM10_Samples/VRM10Viewer/TinyPbrContext.cs
  Assets/VRM10_Samples/VRM10Viewer/TinyPbrDescriptorGenerator.cs
  Assets/VRM10_Samples/VRM10Viewer/TinyPbrMaterialContext.cs
  Assets/VRM10_Samples/VRM10Viewer/TinyPbrMaterialContext.cs.meta
  Assets/VRM10_Samples/VRM10Viewer/TinyPbrMaterialImporter.cs
  Assets/VRM10_Samples/VRM10Viewer/TinyPbrMaterialImporter.cs.meta
  Assets/VRM10_Samples/VRM10Viewer/VRM10Loaded.cs
  Assets/VRM10_Samples/VRM10Viewer/VRM10Viewer.unity
  Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs
Labels: URP, Non breaking changes, WebGL

#2579 call HumanPoseHandler.Dispose
  Assets/UniGLTF/Runtime/UniHumanoid/HumanPoseTransfer.cs
Labels: animation, Non breaking changes

#2580 [Vrma] ForceUniqueName before create AvatarDescription
  Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs
  Assets/UniGLTF/Runtime/UniHumanoid/HumanoidLoader.cs
  Assets/UniGLTF/Runtime/Utils/ForceTransformUniqueName.cs
  Assets/UniGLTF/Runtime/Utils/ForceTransformUniqueName.cs.meta
Labels: importer, animation, Non breaking changes

#2583 UniVRM-0.128.2
  Assets/UniGLTF/Runtime/UniGLTF/PackageVersion.cs
  Assets/UniGLTF/Runtime/UniGLTF/UniGLTFVersion.cs
  Assets/UniGLTF/package.json
  Assets/VRM/Editor/Format/VRMVersionMenu.cs
  Assets/VRM/package.json
  Assets/VRM10/Runtime/Components/Expression/ExpressionMerger.cs
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyMToonAlphaBlend.shadergraph
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyMToonAlphaBlend.shadergraph.meta
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyMToonOpaque.shadergraph
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyMToonOpaque.shadergraph.meta
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyMToon_SubGraph.shadersubgraph
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyMToon_SubGraph.shadersubgraph.meta
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyPbr.shadergraph
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyPbrAlphaBlend.shadergraph
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyPbrAlphaBlend.shadergraph.meta
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyPbrOpaque.shadergraph
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyPbrOpaque.shadergraph.meta
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyPbr_SubGraph.shadersubgraph
  Assets/VRM10/Samples~/VRM10Viewer/Assets/TinyPbr_SubGraph.shadersubgraph.meta
  Assets/VRM10/Samples~/VRM10Viewer/Assets/black.png
  Assets/VRM10/Samples~/VRM10Viewer/Assets/black.png.meta
  Assets/VRM10/Samples~/VRM10Viewer/Assets/blue.png
  Assets/VRM10/Samples~/VRM10Viewer/Assets/blue.png.meta
  Assets/VRM10/Samples~/VRM10Viewer/Assets/red.png
  Assets/VRM10/Samples~/VRM10Viewer/Assets/red.png.meta
  Assets/VRM10/Samples~/VRM10Viewer/Assets/white.png
  Assets/VRM10/Samples~/VRM10Viewer/Assets/white.png.meta
  Assets/VRM10/Samples~/VRM10Viewer/Assets/white_hdr.hdr
  Assets/VRM10/Samples~/VRM10Viewer/Assets/white_hdr.hdr.meta
  Assets/VRM10/Samples~/VRM10Viewer/IMaterialImporter.cs
  Assets/VRM10/Samples~/VRM10Viewer/IMaterialImporter.cs.meta
  Assets/VRM10/Samples~/VRM10Viewer/OrderedMaterialDescriptorGenerator.cs
  Assets/VRM10/Samples~/VRM10Viewer/OrderedMaterialDescriptorGenerator.cs.meta
  Assets/VRM10/Samples~/VRM10Viewer/TinyMToonMaterialContext.cs
  Assets/VRM10/Samples~/VRM10Viewer/TinyMToonMaterialContext.cs.meta
  Assets/VRM10/Samples~/VRM10Viewer/TinyMToonMaterialImporter.cs
  Assets/VRM10/Samples~/VRM10Viewer/TinyMToonMaterialImporter.cs.meta
  Assets/VRM10/Samples~/VRM10Viewer/TinyPbrContext.cs
  Assets/VRM10/Samples~/VRM10Viewer/TinyPbrDescriptorGenerator.cs
  Assets/VRM10/Samples~/VRM10Viewer/TinyPbrMaterialContext.cs
  Assets/VRM10/Samples~/VRM10Viewer/TinyPbrMaterialContext.cs.meta
  Assets/VRM10/Samples~/VRM10Viewer/TinyPbrMaterialImporter.cs
  Assets/VRM10/Samples~/VRM10Viewer/TinyPbrMaterialImporter.cs.meta
  Assets/VRM10/Samples~/VRM10Viewer/VRM10Loaded.cs
  Assets/VRM10/Samples~/VRM10Viewer/VRM10Viewer.unity
  Assets/VRM10/Samples~/VRM10Viewer/VRM10ViewerUI.cs
  Assets/VRM10/package.json
Labels: document/sample, Non breaking changes

#2584 MToonOutlineRenderFeature supports RenderGraph.
  Assets/VRM10/MToon10/Runtime/MToonOutlineRenderFeature.cs
  Assets/VRM10/MToon10/Runtime/MToonOutlineRenderPass.cs
Labels: Non breaking changes

#2585 [URP] fix Vrm10Viewer when RenderPipeLine is built-in.
  Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs
Labels: URP, Non breaking changes

#2586 sample 更新忘れ
  Assets/VRM10/Samples~/VRM10Viewer/VRM10ViewerUI.cs
Labels: document/sample, Non breaking changes

#2587 [LookAt] Vrm1/runtime lookat info
  Assets/VRM10/Editor/Vrm10InstanceEditor.cs
  Assets/VRM10_Samples/VRM10Viewer/VRM10TargetMover.cs
Labels: editor, LookAt/FirstPerson, Non breaking changes

#2589 [LookAt] uv + isbinary と関連する修正
  Assets/VRM10/Editor/Vrm10InstanceEditor.cs
  Assets/VRM10/Runtime/Components/Expression/ExpressionMerger.cs
  Assets/VRM10/Runtime/Components/Expression/MaterialValueBindingMerger.cs
  Assets/VRM10/Runtime/Components/Expression/PreviewMaterialItem.cs
  Assets/VRM10/Runtime/Components/LookAt/Matrix4x4Extensions.cs
  Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs
  Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs
  Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeExpression.cs
  Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeLookAt.cs
  Assets/VRM10/Tests/ExpressionTests.cs
Labels: LookAt/FirstPerson, Non breaking changes

#2591 [LookAt] VRM10ObjectLookAtEditor
  Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs
  Assets/VRM10/Editor/Components/VRM10ObjectEditor.cs
  Assets/VRM10/Editor/Components/VRM10ObjectLookAtEditor.cs
  Assets/VRM10/Editor/Components/VRM10ObjectLookAtEditor.cs.meta
  Assets/VRM10/Editor/Vrm10EditorUtility.cs
  Assets/VRM10/Editor/Vrm10EditorUtility.cs.meta
  Assets/VRM10/Runtime/Components/LookAt/CurveMapper.cs
Labels: editor, LookAt/FirstPerson, Non breaking changes
