Repository vrm-c/UniVRM, pull requests merged in 2025-06, with the labels that each got.

#2670 UniGLTF.MeshData.ImportMeshIndependentVertexBufferのGC Allocを削減
  Assets/UniGLTF/Runtime/Extensions/UnityExtensions.cs
  Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshData.cs
Labels: importer, mesh, Non breaking changes

#2676 UniVRM-0.130.0
  Assets/UniGLTF/Runtime/UniGLTF/PackageVersion.cs
  Assets/UniGLTF/Runtime/UniGLTF/UniGLTFVersion.cs
  Assets/UniGLTF/package.json
  Assets/VRM/package.json
  Assets/VRM10/Samples~/ClothSample/ClothViewer/Motions/BvhMotion.cs
  Assets/VRM10/Samples~/VRM10Viewer/FaceCameraTarget.asset
  Assets/VRM10/Samples~/VRM10Viewer/UIToolkit/VRM10MainView.cs
  Assets/VRM10/Samples~/VRM10Viewer/VRM10ViewerController.cs
  Assets/VRM10/Samples~/VRM10Viewer/VRM10VisualPrimitive.cs
  Assets/VRM10/Samples~/VRM10Viewer/uGui/VRM10ViewerUI.cs
  Assets/VRM10/package.json
  ProjectSettings/Vrm10ProjectEditorSettings.asset
Labels: Breaking changes

#2681 [Unity-2022.3.52f1] UniVRM-0.129.2
  Assets/UniGLTF/Runtime/UniGLTF/PackageVersion.cs
  Assets/UniGLTF/Runtime/UniGLTF/UniGLTFVersion.cs
  Assets/UniGLTF/package.json
  Assets/VRM/package.json
  Assets/VRM10/Samples~/VRM10Viewer/FaceCameraTarget.asset
  Assets/VRM10/package.json
  Assets/VRM10_Samples/VRM10Viewer/FaceCameraTarget.asset
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/ShaderGraphSettings.asset
  ProjectSettings/URPProjectSettings.asset
Labels: Packaging, UnityVersion, Non breaking changes
